### ISSUE TITLE
lua dependency disabled on Mac

### ISSUE THREAD

**Issue by rodhash** [vhyrro/luarocks.nvim#12]
The required version 5.1 is disabled for mac:

```bash
 ❯_ brew install lua@5.1
Error: lua@5.1 has been disabled because it is deprecated upstream!
```

**Comment by vhyrro** [comment]
Wow, this is particularly infuriating. Lua 5.1 is commonly used everywhere, even Neovim can be used with it, so I have no idea why it's considered "deprecated" by the brew community, unless there's an alternative way of installing 5.1 disabling it is silly :p

This makes #2 even more lucrative as a concept.

What about installing with JIT? If you have luajit installed on your system, does the compilation step succeed? I'll get to work on the Neovim interpreter concept in the meantime :)

**Comment by rodhash** [comment]
Found lua binaries in lua.org, and the manual compilation seems to run ok:


```bash
 ❯_ nvim -l build.lua
Build started
⌛ Checking git exists
✅ Checking git exists
⌛ Checking Lua exists
✅ Checking Lua exists
⌛ Cloning luarocks repository with lowest depth
✅ Cloning luarocks repository with lowest depth
⌛ Performing luarocks install.bat if Windows systems
✅ Performing luarocks install.bat if Windows systems
⌛ Performing luarocks `./configure` if Unix systems
✅ Performing luarocks `./configure` if Unix systems
⌛ Performing luarocks `make` if Unix systems
✅ Performing luarocks `make` if Unix systems
⌛ Performing luarocks `make install` if Unix systems
✅ Performing luarocks `make install` if Unix systems
Build completed%
```

**Comment by vhyrro** [comment]
That's nice. #2 seems to be impossible without a vast array of hacks. Instead of that, perhaps it would be wiser to simply vendor a lua directory just like the torch team did a while back. I'm still playing around with ideas :)

**Comment by pm4rcin** [comment]
> That's nice. #2 seems to be impossible without a vast array of hacks. Instead of that, perhaps it would be wiser to simply vendor a lua directory just like the torch team did a while back. I'm still playing around with ideas :)

Can't luajit be used? I'm on Fedora Sway Atomic 39 and it'd be nice if I didn't have to install additional compat package since `lua` rpm package is version 5.4

**Comment by vhyrro** [comment]
Adding LuaJIT support was super simple, so that's exactly what I did. Now everything should function much more smoothly :)
