### ISSUE TITLE
Lua module not found for config of luarocks.nvim. Please use a `config()` function instead

### ISSUE THREAD

**Issue by glyh** [vhyrro/luarocks.nvim#26]
When attempting to install luarocks.nvim I got the following errors:
```
Lua module not found for config of luarocks.nvim. Please use a `config()` function instead
```

**Comment by glyh** [comment]
Looks like `lazy.nvim` is not happy about `config = true`?

**Comment by glyh** [comment]
Removing `config = true` seems to be a fix.

**Comment by vhyrro** [comment]
Weird, are you on some outdated version of lazy perhaps? All CI and my own test configurations make use of `config = true` without issue :)

**Comment by glyh** [comment]
I can no longer reproduce this and I don't know why. Let me close this.
