### ISSUE TITLE
Where does luarocks store its files? 

### ISSUE THREAD

**Issue by glyh** [vhyrro/luarocks.nvim#27]
I checked `~/.luarocks` but it's not present.

**Comment by vhyrro** [comment]
`luarocks.nvim` stores its files in its own directory under `.rocks`, this means it's probably under `~/.local/share/nvim/site/pack/*/*/luarocks.nvim/.rocks` or in the case of lazy `~/.local/share/nvim/lazy/luarocks.nvim/.rocks` :)
