### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by kuznetsss** [vhyrro/luarocks.nvim#4]
Hi, I'm getting error during installation:
```
❌ Installing LuaJIT
Vim:E731: using Dictionary as a String
```

I'm using Neovim 0.9.5 on macos 14.3.1. 

`checkhealth luarocks`:
```
luarocks
- luarocks system is not prepared
- OK python3 is available on PATH, and rocks system is ready to be built
```

Could you please help with it?

**Comment by kang8** [comment]
Same as me.

I'm useing Neovim v0.10.0-dev-2663+gc1c6c1ee1 on MacOS 14.3.1

**Comment by kuznetsss** [comment]
There is something wrong with this `opts`.
https://github.com/vhyrro/luarocks.nvim/blob/dc4f9db72f1ea890e621c6684aea04d565dcac5b/lua/luarocks/build.lua#L46-L53

I tried to comment out the `if is_darwin()` and the error is gone. But I'm not sure whether it broke something else or not.

UPD: checking [system() docs](https://neovim.io/doc/user/builtin.html#system()) it turns out the second argument is `input` for the command but not options.

**Comment by vhyrro** [comment]
Thanks for the error logs! This should now be fixed I believe! Please test on MacOS and let me know if there are any other errors :)

**Comment by vhyrro** [comment]
Closing as fixed!
